language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

# PostGIS Support Matrix: https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS
env:
  # Legacy/EOL PostgreSQL/PostGIS versions
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.2

  # Supported PostgreSQL/PostGIS versions
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.5 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.5 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.6 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.4.0 POSTGRESQL_VERSION=9.6 POSTGIS_VERSION=2.4

  # Legacy/EOL PostgreSQL/PostGIS versions
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.2

  # Supported PostgreSQL/PostGIS versions
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.5 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.5 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.6 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.5.0 POSTGRESQL_VERSION=9.6 POSTGIS_VERSION=2.4

  # Legacy/EOL PostgreSQL/PostGIS versions
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.2

  # Supported PostgreSQL/PostGIS versions
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.5 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.5 POSTGIS_VERSION=2.4

  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.6 POSTGIS_VERSION=2.3
  - DOCTRINE_VERSION=^2.6.0 POSTGRESQL_VERSION=9.6 POSTGIS_VERSION=2.4

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - travis_retry ./travis/install.sh $POSTGRESQL_VERSION $POSTGIS_VERSION
  - composer require doctrine/common doctrine/orm:${DOCTRINE_VERSION}
  - composer show

before_script:
  - travis_retry ./travis/before_script.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

script:
  - vendor/bin/phpunit -c ./travis/phpunit.travis.postgis-$POSTGIS_VERSION.xml -v --coverage-text --coverage-clover ./build/logs/clover.postgis-$POSTGIS_VERSION.xml

after_success:
  - if [ -f ./build/logs/clover.postgis-$POSTGIS_VERSION.xml ]; then travis_retry composer require satooshi/php-coveralls --no-interaction --update-with-dependencies; fi
  - if [ -f ./build/logs/clover.postgis-$POSTGIS_VERSION.xml ]; then php vendor/bin/coveralls -v --coverage_clover ./build/logs/clover.postgis-$POSTGIS_VERSION.xml; fi
